include:
- project: cms-cactus/ops/auto-devops
  ref: 0.0.4
  file: templates/all.yml

# Only run when a branch or git tag is defined
# this avoids accidents like
# - detached pipelines causing undefined behavior
# - triggering for merge requests, where the CI pretends your code is already on the master branch, 
#   and thus you unintentionally push your RPMs to your production yum repo prematurely
workflow:
  rules:
  - if: $CI_COMMIT_TAG
  - if: $CI_COMMIT_BRANCH

variables:
  BASE_IMAGE: gitlab-registry.cern.ch/cms-cactus/core/ts/xdaq15-ts52:master-latest

stages:
- ğŸ—ï¸ build
- ğŸ test
- ğŸ“¦ publish
- ğŸš€ deploy
- ğŸ’£ cleanup

build:
  stage: ğŸ—ï¸ build
  image: $BASE_IMAGE
  before_script:
  - source .gitlab/ci/xdaq-fix-buildpath.sh
  script:
  - cd swatch
  - make Set=all
  - make Set=all rpm
  - cd ..
  - rm -rf ci_rpms && mkdir ci_rpms
  - find . -name "*.rpm" ! -path "./swatch/ci_rpms/*" -exec mv -vn -t ci_rpms/ "{}" +
  artifacts:
    expire_in: 1 day
    paths:
    - ci_rpms
    # https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/1917
    # - ./swatch/**/*.exe
    # - ./swatch/**/*.o
    # - ./swatch/**/*.d
    # - ./swatch/**/*.so
    - ./swatch/*/*/*/*/*.exe
    - ./swatch/*/*/*/*.exe
    - ./swatch/*/*/*.exe
    - ./swatch/*/*/*/*/*.so
    - ./swatch/*/*/*/*.so
    - ./swatch/*/*/*.so
    - ./swatch/*/*/*/*/*.o
    - ./swatch/*/*/*/*.o
    - ./swatch/*/*/*.o
    - ./swatch/*/*/*/*/*.d
    - ./swatch/*/*/*/*.d
    - ./swatch/*/*/*.d

.test_template: &test_template
  stage: ğŸ test
  image: $BASE_IMAGE
  variables:
    TEST_NAME: all
  before_script:
  - .gitlab/ci/make-mark-done.sh
  script:
  - cd swatch
  - make Set=all # in case some build files are missing
  - ../scripts/test.sh $TEST_NAME

unit tests:
  <<: *test_template
  variables:
    TEST_NAME: unit

# BUG: valgrind keeps getting stuck in CI
# retry does not work, gets scheduled to the same worker and happens again
# valgrind:
#   <<: *test_template
#   variables:
#     TEST_NAME: valgrind
#   # Valgrind tests tend to get stuck in CI
#   timeout: 8 minutes
#   retry: 2

mp7:
  <<: *test_template
  variables:
    TEST_NAME: mp7

RPMs:
  stage: ğŸ“¦ publish
  extends: .auto_devops_upload_yum_repo_eos_template
  variables:
    LOCAL_FOLDER: ci_rpms
    CERNBOX_FOLDER: /eos/user/c/cactus/www/cactus/release/unstable/$CI_PROJECT_PATH_SLUG/$CI_COMMIT_REF_NAME/centos7_x86_64/base/RPMS/

RPMs production:
  stage: ğŸ“¦ publish
  # disable auto yum repo db update for now
  # extends: .auto_devops_upload_yum_repo_eos_template
  extends: .auto_devops_upload_eos_template
  # run on push to master, or when triggering pipeline in the ui with $PACKAGE_VER_PATCH set
  # runs on new tag, source of truth is in version.h
  rules:
  - if: $PACKAGE_VER_PATCH || $CI_COMMIT_TAG
    when: on_success
  - when: never
  variables:
    LOCAL_FOLDER: ci_rpms
    CERNBOX_FOLDER: /eos/user/c/cactus/www/cactus/release/swatch/1.3/centos7_x86_64/RPMS

docker:
  stage: ğŸ“¦ publish
  extends: .auto_devops_docker_builder_autotag
  variables:
    # version copied from the various Makefiles
    NAME: xdaq15-swatch13
    BUILD_ARG_BASE_IMAGE: $BASE_IMAGE
    DOCKERFILE: xdaq15.Dockerfile

test:app:
  stage: ğŸš€ deploy
  extends: .auto_devops_k8s_basic_deployment
  image: gitlab-registry.cern.ch/cms-cactus/ops/auto-devops/kubectl:master-093005ee
  variables:
    DOCKER_IMAGE_NAME: xdaq15-swatch13
  environment:
    on_stop: ğŸ’£ test:app

ğŸ’£ test:app:
  stage: ğŸ’£ cleanup
  extends: .auto_devops_k8s_basic_deployment_stop
  dependencies: ["test:app"]
